// Verilated -*- C++ -*-
// DESCRIPTION: Verilator output: Design internal header
// See Vmips_core.h for the primary calling header

#ifndef VERILATED_VMIPS_CORE___024ROOT_H_
#define VERILATED_VMIPS_CORE___024ROOT_H_  // guard

#include "verilated.h"

class Vmips_core__Syms;
class Vmips_core___024unit;
class Vmips_core_hazard_control_ifc;
class Vmips_core_branch_pred_hc_ifc;
class Vmips_core_load_pc_ifc;
class Vmips_core_pc_ifc;
class Vmips_core_inst_q_output_ifc;
class Vmips_core_decoder_output_ifc;
class Vmips_core_rob_reg_wr_ifc;
class Vmips_core_rob_mem_wr_ifc;
class Vmips_core_rob_status_ifc;
class Vmips_core_rob_branch_commit_ifc;
class Vmips_core_rob_jump_reg_commit_ifc;
class Vmips_core_register_rename_ifc;
class Vmips_core_reg_file_output_ifc;
class Vmips_core_alu_res_stat_output_ifc;
class Vmips_core_alu_res_stat_status_ifc;
class Vmips_core_alu_output_ifc;
class Vmips_core_mem_addr_unit_st_output_ifc;
class Vmips_core_mem_res_stat_status_ifc;
class Vmips_core_d_cache_input_ifc;
class Vmips_core_d_cache_output_ifc;
class Vmips_core_common_data_bus_ifc;

VL_MODULE(Vmips_core___024root) {
  public:
    // CELLS
    Vmips_core___024unit* __PVT____024unit;
    Vmips_core_hazard_control_ifc* __PVT__mips_core__DOT__i_hc;
    Vmips_core_hazard_control_ifc* __PVT__mips_core__DOT__d_hc;
    Vmips_core_hazard_control_ifc* __PVT__mips_core__DOT__rob_st_hc;
    Vmips_core_hazard_control_ifc* __PVT__mips_core__DOT__e_hc;
    Vmips_core_hazard_control_ifc* __PVT__mips_core__DOT__m_hc;
    Vmips_core_branch_pred_hc_ifc* __PVT__mips_core__DOT__branch_pred_hc;
    Vmips_core_load_pc_ifc* __PVT__mips_core__DOT__i_load_pc;
    Vmips_core_pc_ifc* __PVT__mips_core__DOT__pc_current;
    Vmips_core_pc_ifc* __PVT__mips_core__DOT__pc_next;
    Vmips_core_inst_q_output_ifc* __PVT__mips_core__DOT__inst_q_output;
    Vmips_core_decoder_output_ifc* __PVT__mips_core__DOT__decoder_output;
    Vmips_core_rob_reg_wr_ifc* __PVT__mips_core__DOT__rob_reg_wr;
    Vmips_core_rob_mem_wr_ifc* __PVT__mips_core__DOT__rob_mem_wr;
    Vmips_core_rob_status_ifc* __PVT__mips_core__DOT__rob_status;
    Vmips_core_rob_branch_commit_ifc* __PVT__mips_core__DOT__rob_branch_commit;
    Vmips_core_rob_jump_reg_commit_ifc* __PVT__mips_core__DOT__rob_jump_reg_commit;
    Vmips_core_register_rename_ifc* __PVT__mips_core__DOT__phy_reg_output;
    Vmips_core_reg_file_output_ifc* __PVT__mips_core__DOT__reg_file_data;
    Vmips_core_alu_res_stat_output_ifc* __PVT__mips_core__DOT__alu_res_stat_output;
    Vmips_core_alu_res_stat_status_ifc* __PVT__mips_core__DOT__alu_res_stat_status;
    Vmips_core_alu_output_ifc* __PVT__mips_core__DOT__alu_output;
    Vmips_core_mem_addr_unit_st_output_ifc* __PVT__mips_core__DOT__st_data_output;
    Vmips_core_mem_res_stat_status_ifc* __PVT__mips_core__DOT__mem_res_stat_status;
    Vmips_core_d_cache_input_ifc* __PVT__mips_core__DOT__d_cache_input;
    Vmips_core_d_cache_output_ifc* __PVT__mips_core__DOT__d_cache_output;
    Vmips_core_common_data_bus_ifc* __PVT__mips_core__DOT__cdb_output;

    // DESIGN SPECIFIC STATE
    // Anonymous structures to workaround compiler member-count bugs
    struct {
        VL_IN8(clk,0,0);
        VL_IN8(rst_n,0,0);
        VL_OUT8(done,0,0);
        VL_IN8(AWREADY,0,0);
        VL_OUT8(AWVALID,0,0);
        VL_OUT8(AWID,3,0);
        VL_OUT8(AWLEN,3,0);
        VL_IN8(WREADY,0,0);
        VL_OUT8(WVALID,0,0);
        VL_OUT8(WLAST,0,0);
        VL_OUT8(WID,3,0);
        VL_OUT8(BREADY,0,0);
        VL_IN8(BVALID,0,0);
        VL_IN8(BID,3,0);
        VL_IN8(ARREADY,0,0);
        VL_OUT8(ARVALID,0,0);
        VL_OUT8(ARID,3,0);
        VL_OUT8(ARLEN,3,0);
        VL_OUT8(RREADY,0,0);
        VL_IN8(RVALID,0,0);
        VL_IN8(RLAST,0,0);
        VL_IN8(RID,3,0);
        CData/*1:0*/ mips_core__DOT__I_CACHE__DOT__state;
        CData/*1:0*/ mips_core__DOT__I_CACHE__DOT__next_state;
        CData/*5:0*/ mips_core__DOT__I_CACHE__DOT__r_index;
        CData/*3:0*/ mips_core__DOT__I_CACHE__DOT__databank_select;
        CData/*3:0*/ mips_core__DOT__I_CACHE__DOT__databank_we;
        CData/*0:0*/ mips_core__DOT__I_CACHE__DOT__victim_hit;
        CData/*0:0*/ mips_core__DOT__I_CACHE__DOT__victim_wr_en;
        CData/*0:0*/ mips_core__DOT__I_CACHE__DOT__main_cache_hit;
        CData/*0:0*/ mips_core__DOT__I_CACHE__DOT__hit;
        CData/*0:0*/ mips_core__DOT__I_CACHE__DOT__miss;
        CData/*0:0*/ mips_core__DOT__I_CACHE__DOT__last_refill_word;
        CData/*1:0*/ mips_core__DOT__I_CACHE__DOT__victim_cache__DOT__victim;
        CData/*0:0*/ mips_core__DOT__I_CACHE__DOT__tagbank__DOT__new_data_flag;
        CData/*0:0*/ mips_core__DOT__I_CACHE__DOT__tagbank__DOT__genblk1__DOT__BANK_CORE__DOT__csb0_reg;
        CData/*5:0*/ mips_core__DOT__I_CACHE__DOT__tagbank__DOT__genblk1__DOT__BANK_CORE__DOT__addr0_reg;
        CData/*0:0*/ mips_core__DOT__I_CACHE__DOT__tagbank__DOT__genblk1__DOT__BANK_CORE__DOT__csb1_reg;
        CData/*5:0*/ mips_core__DOT__I_CACHE__DOT__tagbank__DOT__genblk1__DOT__BANK_CORE__DOT__addr1_reg;
        CData/*0:0*/ mips_core__DOT__I_CACHE__DOT__databanks__BRA__0__KET____DOT__databank__DOT__new_data_flag;
        CData/*0:0*/ mips_core__DOT__I_CACHE__DOT__databanks__BRA__0__KET____DOT__databank__DOT__genblk1__DOT__BANK_CORE__DOT__csb0_reg;
        CData/*5:0*/ mips_core__DOT__I_CACHE__DOT__databanks__BRA__0__KET____DOT__databank__DOT__genblk1__DOT__BANK_CORE__DOT__addr0_reg;
        CData/*0:0*/ mips_core__DOT__I_CACHE__DOT__databanks__BRA__0__KET____DOT__databank__DOT__genblk1__DOT__BANK_CORE__DOT__csb1_reg;
        CData/*5:0*/ mips_core__DOT__I_CACHE__DOT__databanks__BRA__0__KET____DOT__databank__DOT__genblk1__DOT__BANK_CORE__DOT__addr1_reg;
        CData/*0:0*/ mips_core__DOT__I_CACHE__DOT__databanks__BRA__1__KET____DOT__databank__DOT__new_data_flag;
        CData/*0:0*/ mips_core__DOT__I_CACHE__DOT__databanks__BRA__1__KET____DOT__databank__DOT__genblk1__DOT__BANK_CORE__DOT__csb0_reg;
        CData/*5:0*/ mips_core__DOT__I_CACHE__DOT__databanks__BRA__1__KET____DOT__databank__DOT__genblk1__DOT__BANK_CORE__DOT__addr0_reg;
        CData/*0:0*/ mips_core__DOT__I_CACHE__DOT__databanks__BRA__1__KET____DOT__databank__DOT__genblk1__DOT__BANK_CORE__DOT__csb1_reg;
        CData/*5:0*/ mips_core__DOT__I_CACHE__DOT__databanks__BRA__1__KET____DOT__databank__DOT__genblk1__DOT__BANK_CORE__DOT__addr1_reg;
        CData/*0:0*/ mips_core__DOT__I_CACHE__DOT__databanks__BRA__2__KET____DOT__databank__DOT__new_data_flag;
        CData/*0:0*/ mips_core__DOT__I_CACHE__DOT__databanks__BRA__2__KET____DOT__databank__DOT__genblk1__DOT__BANK_CORE__DOT__csb0_reg;
        CData/*5:0*/ mips_core__DOT__I_CACHE__DOT__databanks__BRA__2__KET____DOT__databank__DOT__genblk1__DOT__BANK_CORE__DOT__addr0_reg;
        CData/*0:0*/ mips_core__DOT__I_CACHE__DOT__databanks__BRA__2__KET____DOT__databank__DOT__genblk1__DOT__BANK_CORE__DOT__csb1_reg;
        CData/*5:0*/ mips_core__DOT__I_CACHE__DOT__databanks__BRA__2__KET____DOT__databank__DOT__genblk1__DOT__BANK_CORE__DOT__addr1_reg;
        CData/*0:0*/ mips_core__DOT__I_CACHE__DOT__databanks__BRA__3__KET____DOT__databank__DOT__new_data_flag;
        CData/*0:0*/ mips_core__DOT__I_CACHE__DOT__databanks__BRA__3__KET____DOT__databank__DOT__genblk1__DOT__BANK_CORE__DOT__csb0_reg;
        CData/*5:0*/ mips_core__DOT__I_CACHE__DOT__databanks__BRA__3__KET____DOT__databank__DOT__genblk1__DOT__BANK_CORE__DOT__addr0_reg;
        CData/*0:0*/ mips_core__DOT__I_CACHE__DOT__databanks__BRA__3__KET____DOT__databank__DOT__genblk1__DOT__BANK_CORE__DOT__csb1_reg;
        CData/*5:0*/ mips_core__DOT__I_CACHE__DOT__databanks__BRA__3__KET____DOT__databank__DOT__genblk1__DOT__BANK_CORE__DOT__addr1_reg;
        CData/*1:0*/ mips_core__DOT__INSTRUCTION_QUEUE__DOT__wr_ptr;
        CData/*1:0*/ mips_core__DOT__INSTRUCTION_QUEUE__DOT__rd_ptr;
        CData/*0:0*/ mips_core__DOT__INSTRUCTION_QUEUE__DOT__full;
        CData/*0:0*/ mips_core__DOT__INSTRUCTION_QUEUE__DOT__empty;
        CData/*0:0*/ mips_core__DOT__REGISTER_RENAME__DOT__ch_wr_ptr;
    };
    struct {
        CData/*0:0*/ mips_core__DOT__REGISTER_RENAME__DOT__ch_rd_ptr;
        CData/*5:0*/ mips_core__DOT__REGISTER_RENAME__DOT__free_phy_reg;
        CData/*0:0*/ mips_core__DOT__REGISTER_RENAME__DOT__avail_reg;
        CData/*0:0*/ mips_core__DOT__REGISTER_RENAME__DOT____Vlvbound_hd1090cd5__0;
        CData/*0:0*/ mips_core__DOT__REGISTER_RENAME__DOT____Vlvbound_h52e43eaf__0;
        CData/*1:0*/ mips_core__DOT__REORDER_BUFFER__DOT__INSTRUCTION_TYPE;
        CData/*1:0*/ mips_core__DOT__REORDER_BUFFER__DOT__wr_ptr;
        CData/*1:0*/ mips_core__DOT__REORDER_BUFFER__DOT__rd_ptr;
        CData/*0:0*/ mips_core__DOT__REORDER_BUFFER__DOT__empty_spot;
        CData/*1:0*/ mips_core__DOT__REORDER_BUFFER__DOT__input_inst_type;
        CData/*0:0*/ mips_core__DOT__REORDER_BUFFER__DOT__full;
        CData/*0:0*/ mips_core__DOT__REORDER_BUFFER__DOT__top_ready;
        CData/*0:0*/ mips_core__DOT__ALU_RESERVATION_STATION__DOT__full;
        CData/*0:0*/ mips_core__DOT__ALU_RESERVATION_STATION__DOT__ready;
        CData/*0:0*/ mips_core__DOT__ALU_RESERVATION_STATION__DOT__write_index;
        CData/*0:0*/ mips_core__DOT__ALU_RESERVATION_STATION__DOT__ready_index;
        CData/*0:0*/ mips_core__DOT__MEM_RESERVATION_STATION__DOT__sq_wr_ptr;
        CData/*0:0*/ mips_core__DOT__MEM_RESERVATION_STATION__DOT__sq_rd_ptr;
        CData/*1:0*/ mips_core__DOT__MEM_RESERVATION_STATION__DOT__wr_ptr;
        CData/*1:0*/ mips_core__DOT__MEM_RESERVATION_STATION__DOT__rd_ptr;
        CData/*0:0*/ mips_core__DOT__MEM_RESERVATION_STATION__DOT__empty_spot;
        CData/*0:0*/ mips_core__DOT__MEM_RESERVATION_STATION__DOT__full;
        CData/*0:0*/ mips_core__DOT__MEM_RESERVATION_STATION__DOT__empty;
        CData/*0:0*/ mips_core__DOT__MEM_RESERVATION_STATION__DOT__ready;
        CData/*0:0*/ mips_core__DOT__MEM_RESERVATION_STATION__DOT__st_ready;
        CData/*0:0*/ mips_core__DOT__MEM_RESERVATION_STATION__DOT__ld_ready;
        CData/*0:0*/ mips_core__DOT__MEM_RESERVATION_STATION__DOT__mem_input_valid_reg;
        CData/*0:0*/ mips_core__DOT__MEM_RESERVATION_STATION__DOT__mem_action_reg;
        CData/*0:0*/ mips_core__DOT__MEM_RESERVATION_STATION__DOT__tag_reg;
        CData/*2:0*/ mips_core__DOT__D_CACHE__DOT__state;
        CData/*2:0*/ mips_core__DOT__D_CACHE__DOT__next_state;
        CData/*0:0*/ mips_core__DOT__D_CACHE__DOT__pending_write_response;
        CData/*5:0*/ mips_core__DOT__D_CACHE__DOT__r_index;
        CData/*3:0*/ mips_core__DOT__D_CACHE__DOT__databank_select;
        CData/*3:0*/ mips_core__DOT__D_CACHE__DOT__databank_we;
        CData/*5:0*/ mips_core__DOT__D_CACHE__DOT__databank_waddr;
        CData/*5:0*/ mips_core__DOT__D_CACHE__DOT__databank_raddr;
        CData/*0:0*/ mips_core__DOT__D_CACHE__DOT__hit;
        CData/*0:0*/ mips_core__DOT__D_CACHE__DOT__miss;
        CData/*0:0*/ mips_core__DOT__D_CACHE__DOT__last_flush_word;
        CData/*0:0*/ mips_core__DOT__D_CACHE__DOT__last_refill_word;
        CData/*0:0*/ mips_core__DOT__D_CACHE__DOT__tagbank__DOT__new_data_flag;
        CData/*0:0*/ mips_core__DOT__D_CACHE__DOT__tagbank__DOT__genblk1__DOT__BANK_CORE__DOT__csb0_reg;
        CData/*5:0*/ mips_core__DOT__D_CACHE__DOT__tagbank__DOT__genblk1__DOT__BANK_CORE__DOT__addr0_reg;
        CData/*5:0*/ mips_core__DOT__D_CACHE__DOT__tagbank__DOT__genblk1__DOT__BANK_CORE__DOT__addr1_reg;
        CData/*0:0*/ mips_core__DOT__D_CACHE__DOT__databanks__BRA__0__KET____DOT__databank__DOT__new_data_flag;
        CData/*0:0*/ mips_core__DOT__D_CACHE__DOT__databanks__BRA__0__KET____DOT__databank__DOT__genblk1__DOT__BANK_CORE__DOT__csb0_reg;
        CData/*5:0*/ mips_core__DOT__D_CACHE__DOT__databanks__BRA__0__KET____DOT__databank__DOT__genblk1__DOT__BANK_CORE__DOT__addr0_reg;
        CData/*0:0*/ mips_core__DOT__D_CACHE__DOT__databanks__BRA__0__KET____DOT__databank__DOT__genblk1__DOT__BANK_CORE__DOT__csb1_reg;
        CData/*5:0*/ mips_core__DOT__D_CACHE__DOT__databanks__BRA__0__KET____DOT__databank__DOT__genblk1__DOT__BANK_CORE__DOT__addr1_reg;
        CData/*0:0*/ mips_core__DOT__D_CACHE__DOT__databanks__BRA__1__KET____DOT__databank__DOT__new_data_flag;
        CData/*0:0*/ mips_core__DOT__D_CACHE__DOT__databanks__BRA__1__KET____DOT__databank__DOT__genblk1__DOT__BANK_CORE__DOT__csb0_reg;
        CData/*5:0*/ mips_core__DOT__D_CACHE__DOT__databanks__BRA__1__KET____DOT__databank__DOT__genblk1__DOT__BANK_CORE__DOT__addr0_reg;
        CData/*0:0*/ mips_core__DOT__D_CACHE__DOT__databanks__BRA__1__KET____DOT__databank__DOT__genblk1__DOT__BANK_CORE__DOT__csb1_reg;
        CData/*5:0*/ mips_core__DOT__D_CACHE__DOT__databanks__BRA__1__KET____DOT__databank__DOT__genblk1__DOT__BANK_CORE__DOT__addr1_reg;
        CData/*0:0*/ mips_core__DOT__D_CACHE__DOT__databanks__BRA__2__KET____DOT__databank__DOT__new_data_flag;
        CData/*0:0*/ mips_core__DOT__D_CACHE__DOT__databanks__BRA__2__KET____DOT__databank__DOT__genblk1__DOT__BANK_CORE__DOT__csb0_reg;
        CData/*5:0*/ mips_core__DOT__D_CACHE__DOT__databanks__BRA__2__KET____DOT__databank__DOT__genblk1__DOT__BANK_CORE__DOT__addr0_reg;
        CData/*0:0*/ mips_core__DOT__D_CACHE__DOT__databanks__BRA__2__KET____DOT__databank__DOT__genblk1__DOT__BANK_CORE__DOT__csb1_reg;
        CData/*5:0*/ mips_core__DOT__D_CACHE__DOT__databanks__BRA__2__KET____DOT__databank__DOT__genblk1__DOT__BANK_CORE__DOT__addr1_reg;
        CData/*0:0*/ mips_core__DOT__D_CACHE__DOT__databanks__BRA__3__KET____DOT__databank__DOT__new_data_flag;
        CData/*0:0*/ mips_core__DOT__D_CACHE__DOT__databanks__BRA__3__KET____DOT__databank__DOT__genblk1__DOT__BANK_CORE__DOT__csb0_reg;
        CData/*5:0*/ mips_core__DOT__D_CACHE__DOT__databanks__BRA__3__KET____DOT__databank__DOT__genblk1__DOT__BANK_CORE__DOT__addr0_reg;
        CData/*0:0*/ mips_core__DOT__D_CACHE__DOT__databanks__BRA__3__KET____DOT__databank__DOT__genblk1__DOT__BANK_CORE__DOT__csb1_reg;
    };
    struct {
        CData/*5:0*/ mips_core__DOT__D_CACHE__DOT__databanks__BRA__3__KET____DOT__databank__DOT__genblk1__DOT__BANK_CORE__DOT__addr1_reg;
        CData/*0:0*/ mips_core__DOT__COMMON_DATA_BUS__DOT__mem_valid;
        CData/*0:0*/ mips_core__DOT__HAZARD_CONTROLLER__DOT__JR_STATE_LOGIC;
        CData/*0:0*/ mips_core__DOT__HAZARD_CONTROLLER__DOT__bp_wr_ptr;
        CData/*0:0*/ mips_core__DOT__HAZARD_CONTROLLER__DOT__bp_rd_ptr;
        CData/*0:0*/ mips_core__DOT__HAZARD_CONTROLLER__DOT__ic_miss;
        CData/*0:0*/ mips_core__DOT__HAZARD_CONTROLLER__DOT__dec_overload;
        CData/*0:0*/ mips_core__DOT__HAZARD_CONTROLLER__DOT__jr_overload;
        CData/*0:0*/ mips_core__DOT__HAZARD_CONTROLLER__DOT__ex_overload;
        CData/*0:0*/ mips_core__DOT__HAZARD_CONTROLLER__DOT__dc_miss;
        CData/*0:0*/ mips_core__DOT__HAZARD_CONTROLLER__DOT__inst_q_full;
        CData/*0:0*/ mips_core__DOT__HAZARD_CONTROLLER__DOT__rob_full;
        CData/*0:0*/ mips_core__DOT__HAZARD_CONTROLLER__DOT__alu_res_full;
        CData/*0:0*/ mips_core__DOT__HAZARD_CONTROLLER__DOT__mem_res_full;
        CData/*0:0*/ mips_core__DOT__HAZARD_CONTROLLER__DOT__ld_ready_st_stall;
        CData/*0:0*/ mips_core__DOT__HAZARD_CONTROLLER__DOT__req_valid;
        CData/*0:0*/ mips_core__DOT__HAZARD_CONTROLLER__DOT__jr_stall;
        CData/*0:0*/ mips_core__DOT__HAZARD_CONTROLLER__DOT__jr_state;
        CData/*0:0*/ mips_core__DOT__HAZARD_CONTROLLER__DOT__if_stall;
        CData/*0:0*/ mips_core__DOT__HAZARD_CONTROLLER__DOT__if_flush;
        CData/*0:0*/ mips_core__DOT__HAZARD_CONTROLLER__DOT__dec_stall;
        CData/*0:0*/ mips_core__DOT__HAZARD_CONTROLLER__DOT__dec_flush;
        CData/*0:0*/ mips_core__DOT__HAZARD_CONTROLLER__DOT__ex_stall;
        CData/*0:0*/ mips_core__DOT__HAZARD_CONTROLLER__DOT__ex_flush;
        CData/*0:0*/ mips_core__DOT__HAZARD_CONTROLLER__DOT__mem_stall;
        CData/*0:0*/ mips_core__DOT__HAZARD_CONTROLLER__DOT__mem_flush;
        CData/*1:0*/ mips_core__DOT__HAZARD_CONTROLLER__DOT__BRANCH_CONTROLLER__DOT__PREDICTOR__DOT__TAKEN_COUNTER;
        CData/*1:0*/ mips_core__DOT__HAZARD_CONTROLLER__DOT__BRANCH_CONTROLLER__DOT__PREDICTOR__DOT__GSHARE_VS_2BIT_COUNTER;
        CData/*1:0*/ mips_core__DOT__HAZARD_CONTROLLER__DOT__BRANCH_CONTROLLER__DOT__PREDICTOR__DOT__counter;
        CData/*0:0*/ mips_core__DOT__HAZARD_CONTROLLER__DOT__BRANCH_CONTROLLER__DOT__PREDICTOR__DOT__gshare_pred;
        CData/*0:0*/ mips_core__DOT__HAZARD_CONTROLLER__DOT__BRANCH_CONTROLLER__DOT__PREDICTOR__DOT__two_bit_local_pred;
        CData/*0:0*/ mips_core__DOT__HAZARD_CONTROLLER__DOT__BRANCH_CONTROLLER__DOT__PREDICTOR__DOT__chooser_pred;
        CData/*0:0*/ mips_core__DOT__HAZARD_CONTROLLER__DOT__BRANCH_CONTROLLER__DOT__PREDICTOR__DOT__gshare_correct;
        CData/*0:0*/ mips_core__DOT__HAZARD_CONTROLLER__DOT__BRANCH_CONTROLLER__DOT__PREDICTOR__DOT__cur_pred;
        CData/*0:0*/ mips_core__DOT__MEMORY_ARBITER__DOT____Vcellout__write_address_arbiter__valid;
        CData/*0:0*/ mips_core__DOT__MEMORY_ARBITER__DOT____Vcellout__write_data_arbiter__valid;
        CData/*0:0*/ mips_core__DOT__MEMORY_ARBITER__DOT____Vcellout__write_response_splitter__ready;
        CData/*0:0*/ mips_core__DOT__MEMORY_ARBITER__DOT____Vcellout__read_address_arbiter__valid;
        CData/*0:0*/ mips_core__DOT__MEMORY_ARBITER__DOT____Vcellout__read_data_splitter__ready;
        CData/*0:0*/ mips_core__DOT__MEMORY_ARBITER__DOT__write_address_arbiter__DOT__merged_valid;
        CData/*0:0*/ mips_core__DOT__MEMORY_ARBITER__DOT__write_address_arbiter__DOT__merged_ready;
        CData/*0:0*/ mips_core__DOT__MEMORY_ARBITER__DOT__write_data_arbiter__DOT__merged_valid;
        CData/*0:0*/ mips_core__DOT__MEMORY_ARBITER__DOT__write_data_arbiter__DOT__merged_ready;
        CData/*3:0*/ mips_core__DOT__MEMORY_ARBITER__DOT__write_response_splitter__DOT__pipe_payload;
        CData/*0:0*/ mips_core__DOT__MEMORY_ARBITER__DOT__write_response_splitter__DOT__pipe_valid;
        CData/*0:0*/ mips_core__DOT__MEMORY_ARBITER__DOT__write_response_splitter__DOT__pipe_ready;
        CData/*3:0*/ mips_core__DOT__MEMORY_ARBITER__DOT__write_response_splitter__DOT__pipe_id;
        CData/*0:0*/ mips_core__DOT__MEMORY_ARBITER__DOT__read_address_arbiter__DOT__merged_valid;
        CData/*0:0*/ mips_core__DOT__MEMORY_ARBITER__DOT__read_address_arbiter__DOT__merged_ready;
        CData/*0:0*/ mips_core__DOT__MEMORY_ARBITER__DOT__read_data_splitter__DOT__pipe_valid;
        CData/*0:0*/ mips_core__DOT__MEMORY_ARBITER__DOT__read_data_splitter__DOT__pipe_ready;
        CData/*3:0*/ mips_core__DOT__MEMORY_ARBITER__DOT__read_data_splitter__DOT__pipe_id;
        CData/*4:0*/ __Vtask_mips_core__DOT__DECODER__DOT__rw_raw__10__rw;
        CData/*4:0*/ __Vtask_mips_core__DOT__DECODER__DOT__rw_raw__17__rw;
        CData/*4:0*/ __Vtask_mips_core__DOT__DECODER__DOT__rw_raw__22__rw;
        CData/*4:0*/ __Vtask_mips_core__DOT__DECODER__DOT__rw_raw__28__rw;
        CData/*4:0*/ __Vtask_mips_core__DOT__DECODER__DOT__rw_raw__34__rw;
        CData/*4:0*/ __Vtask_mips_core__DOT__DECODER__DOT__rw_raw__40__rw;
        CData/*4:0*/ __Vtask_mips_core__DOT__DECODER__DOT__rw_raw__46__rw;
        CData/*4:0*/ __Vtask_mips_core__DOT__DECODER__DOT__rw_raw__52__rw;
        CData/*4:0*/ __Vtask_mips_core__DOT__DECODER__DOT__rw_raw__58__rw;
        CData/*4:0*/ __Vtask_mips_core__DOT__DECODER__DOT__rw_raw__77__rw;
        CData/*4:0*/ __Vtask_mips_core__DOT__DECODER__DOT__rw_raw__82__rw;
        CData/*4:0*/ __Vtask_mips_core__DOT__DECODER__DOT__rw_raw__87__rw;
    };
    struct {
        CData/*4:0*/ __Vtask_mips_core__DOT__DECODER__DOT__rw_raw__92__rw;
        CData/*4:0*/ __Vtask_mips_core__DOT__DECODER__DOT__rw_raw__97__rw;
        CData/*4:0*/ __Vtask_mips_core__DOT__DECODER__DOT__rw_raw__102__rw;
        CData/*4:0*/ __Vtask_mips_core__DOT__DECODER__DOT__rw_raw__107__rw;
        CData/*4:0*/ __Vtask_mips_core__DOT__DECODER__DOT__rw_raw__112__rw;
        CData/*4:0*/ __Vtask_mips_core__DOT__DECODER__DOT__rw_raw__117__rw;
        CData/*4:0*/ __Vtask_mips_core__DOT__DECODER__DOT__rw_raw__122__rw;
        CData/*4:0*/ __Vtask_mips_core__DOT__DECODER__DOT__rw_raw__131__rw;
        CData/*4:0*/ __Vtask_mips_core__DOT__DECODER__DOT__rw_raw__136__rw;
        CData/*4:0*/ __Vtask_mips_core__DOT__DECODER__DOT__rw_raw__141__rw;
        CData/*4:0*/ __Vtask_mips_core__DOT__DECODER__DOT__rw_raw__145__rw;
        CData/*4:0*/ __Vtask_mips_core__DOT__DECODER__DOT__rw_raw__151__rw;
        CData/*4:0*/ __Vtask_mips_core__DOT__DECODER__DOT__rw_raw__157__rw;
        CData/*6:0*/ __Vfunc_mips_core__DOT__REGISTER_RENAME__DOT__first_free_phy_reg__160__Vfuncout;
        CData/*6:0*/ __Vfunc_mips_core__DOT__REGISTER_RENAME__DOT__first_free_phy_reg__161__Vfuncout;
        CData/*1:0*/ __Vfunc_mips_core__DOT__ALU_RESERVATION_STATION__DOT__check_full__162__Vfuncout;
        CData/*1:0*/ __Vfunc_mips_core__DOT__ALU_RESERVATION_STATION__DOT__check_full__163__Vfuncout;
        CData/*1:0*/ __Vfunc_mips_core__DOT__ALU_RESERVATION_STATION__DOT__get_ready_index__164__Vfuncout;
        CData/*1:0*/ __Vfunc_mips_core__DOT__ALU_RESERVATION_STATION__DOT__get_ready_index__165__Vfuncout;
        CData/*0:0*/ __Vfunc_mips_core__DOT__MEM_RESERVATION_STATION__DOT__address_match__166__Vfuncout;
        CData/*0:0*/ __Vclklast__TOP__clk;
        CData/*5:0*/ __Vchglast__TOP__mips_core__DOT__REGISTER_RENAME__DOT__free_phy_reg;
        CData/*0:0*/ __Vchglast__TOP__mips_core__DOT__d_hc__stall;
        SData/*15:0*/ mips_core__DOT__I_CACHE__DOT__r_tag;
        SData/*15:0*/ mips_core__DOT__I_CACHE__DOT__victim_tag;
        SData/*15:0*/ mips_core__DOT__I_CACHE__DOT__victim_tag_output;
        SData/*15:0*/ mips_core__DOT__I_CACHE__DOT__tagbank_wdata;
        SData/*15:0*/ mips_core__DOT__I_CACHE__DOT__tagbank_rdata;
        SData/*15:0*/ mips_core__DOT__I_CACHE__DOT__tagbank__DOT__new_data;
        SData/*15:0*/ mips_core__DOT__I_CACHE__DOT__tagbank__DOT__old_data;
        SData/*15:0*/ mips_core__DOT__I_CACHE__DOT__tagbank__DOT__genblk1__DOT__BANK_CORE__DOT__din0_reg;
        SData/*15:0*/ mips_core__DOT__D_CACHE__DOT__r_tag;
        SData/*15:0*/ mips_core__DOT__D_CACHE__DOT__tagbank_rdata;
        SData/*15:0*/ mips_core__DOT__D_CACHE__DOT__tagbank__DOT__new_data;
        SData/*15:0*/ mips_core__DOT__D_CACHE__DOT__tagbank__DOT__old_data;
        SData/*15:0*/ mips_core__DOT__D_CACHE__DOT__tagbank__DOT__genblk1__DOT__BANK_CORE__DOT__din0_reg;
        SData/*11:0*/ mips_core__DOT__HAZARD_CONTROLLER__DOT__BRANCH_CONTROLLER__DOT__PREDICTOR__DOT__ghistory;
        SData/*11:0*/ mips_core__DOT__HAZARD_CONTROLLER__DOT__BRANCH_CONTROLLER__DOT__PREDICTOR__DOT__predict_index_gshare;
        SData/*11:0*/ mips_core__DOT__HAZARD_CONTROLLER__DOT__BRANCH_CONTROLLER__DOT__PREDICTOR__DOT__predict_index_chooser;
        SData/*11:0*/ mips_core__DOT__HAZARD_CONTROLLER__DOT__BRANCH_CONTROLLER__DOT__PREDICTOR__DOT__feedback_index_gshare;
        SData/*11:0*/ mips_core__DOT__HAZARD_CONTROLLER__DOT__BRANCH_CONTROLLER__DOT__PREDICTOR__DOT__feedback_index_chooser;
        VL_OUT(AWADDR,25,0);
        VL_OUT(WDATA,31,0);
        VL_OUT(ARADDR,25,0);
        VL_IN(RDATA,31,0);
        IData/*31:0*/ mips_core__DOT__I_CACHE__DOT__victim_cache__DOT__unnamedblk1__DOT__j;
        IData/*31:0*/ mips_core__DOT__I_CACHE__DOT__victim_cache__DOT__unnamedblk3__DOT__i;
        IData/*31:0*/ mips_core__DOT__I_CACHE__DOT__victim_cache__DOT__unnamedblk3__DOT__unnamedblk4__DOT__j;
        IData/*31:0*/ mips_core__DOT__I_CACHE__DOT__databanks__BRA__0__KET____DOT__databank__DOT__new_data;
        IData/*31:0*/ mips_core__DOT__I_CACHE__DOT__databanks__BRA__0__KET____DOT__databank__DOT__old_data;
        IData/*31:0*/ mips_core__DOT__I_CACHE__DOT__databanks__BRA__0__KET____DOT__databank__DOT__genblk1__DOT__BANK_CORE__DOT__din0_reg;
        IData/*31:0*/ mips_core__DOT__I_CACHE__DOT__databanks__BRA__1__KET____DOT__databank__DOT__new_data;
        IData/*31:0*/ mips_core__DOT__I_CACHE__DOT__databanks__BRA__1__KET____DOT__databank__DOT__old_data;
        IData/*31:0*/ mips_core__DOT__I_CACHE__DOT__databanks__BRA__1__KET____DOT__databank__DOT__genblk1__DOT__BANK_CORE__DOT__din0_reg;
        IData/*31:0*/ mips_core__DOT__I_CACHE__DOT__databanks__BRA__2__KET____DOT__databank__DOT__new_data;
        IData/*31:0*/ mips_core__DOT__I_CACHE__DOT__databanks__BRA__2__KET____DOT__databank__DOT__old_data;
        IData/*31:0*/ mips_core__DOT__I_CACHE__DOT__databanks__BRA__2__KET____DOT__databank__DOT__genblk1__DOT__BANK_CORE__DOT__din0_reg;
        IData/*31:0*/ mips_core__DOT__I_CACHE__DOT__databanks__BRA__3__KET____DOT__databank__DOT__new_data;
        IData/*31:0*/ mips_core__DOT__I_CACHE__DOT__databanks__BRA__3__KET____DOT__databank__DOT__old_data;
        IData/*31:0*/ mips_core__DOT__I_CACHE__DOT__databanks__BRA__3__KET____DOT__databank__DOT__genblk1__DOT__BANK_CORE__DOT__din0_reg;
        IData/*31:0*/ mips_core__DOT__REGISTER_RENAME__DOT__unnamedblk5__DOT__i;
        IData/*31:0*/ mips_core__DOT__REGISTER_RENAME__DOT__unnamedblk6__DOT__j;
        IData/*31:0*/ mips_core__DOT__REGISTER_RENAME__DOT__unnamedblk7__DOT__i;
        IData/*31:0*/ mips_core__DOT__REGISTER_RENAME__DOT__unnamedblk8__DOT__j;
    };
    struct {
        IData/*31:0*/ mips_core__DOT__REGISTER_RENAME__DOT__unnamedblk2__DOT__i;
        IData/*31:0*/ mips_core__DOT__REGISTER_RENAME__DOT__unnamedblk3__DOT__j;
        IData/*31:0*/ mips_core__DOT__REGISTER_RENAME__DOT__unnamedblk4__DOT__k;
        IData/*31:0*/ mips_core__DOT__ALU_RESERVATION_STATION__DOT__unnamedblk3__DOT__a;
        IData/*25:0*/ mips_core__DOT__MEM_RESERVATION_STATION__DOT__addr_reg;
        IData/*25:0*/ mips_core__DOT__MEM_RESERVATION_STATION__DOT__addr_next_reg;
        IData/*31:0*/ mips_core__DOT__MEM_RESERVATION_STATION__DOT__data_reg;
        IData/*31:0*/ mips_core__DOT__MEM_RESERVATION_STATION__DOT__unnamedblk1__DOT__a;
        IData/*31:0*/ mips_core__DOT__D_CACHE__DOT__databank_wdata;
        IData/*31:0*/ mips_core__DOT__D_CACHE__DOT__unnamedblk1__DOT__i;
        IData/*31:0*/ mips_core__DOT__D_CACHE__DOT__unnamedblk2__DOT__i;
        IData/*31:0*/ mips_core__DOT__D_CACHE__DOT__databanks__BRA__0__KET____DOT__databank__DOT__new_data;
        IData/*31:0*/ mips_core__DOT__D_CACHE__DOT__databanks__BRA__0__KET____DOT__databank__DOT__old_data;
        IData/*31:0*/ mips_core__DOT__D_CACHE__DOT__databanks__BRA__0__KET____DOT__databank__DOT__genblk1__DOT__BANK_CORE__DOT__din0_reg;
        IData/*31:0*/ mips_core__DOT__D_CACHE__DOT__databanks__BRA__1__KET____DOT__databank__DOT__new_data;
        IData/*31:0*/ mips_core__DOT__D_CACHE__DOT__databanks__BRA__1__KET____DOT__databank__DOT__old_data;
        IData/*31:0*/ mips_core__DOT__D_CACHE__DOT__databanks__BRA__1__KET____DOT__databank__DOT__genblk1__DOT__BANK_CORE__DOT__din0_reg;
        IData/*31:0*/ mips_core__DOT__D_CACHE__DOT__databanks__BRA__2__KET____DOT__databank__DOT__new_data;
        IData/*31:0*/ mips_core__DOT__D_CACHE__DOT__databanks__BRA__2__KET____DOT__databank__DOT__old_data;
        IData/*31:0*/ mips_core__DOT__D_CACHE__DOT__databanks__BRA__2__KET____DOT__databank__DOT__genblk1__DOT__BANK_CORE__DOT__din0_reg;
        IData/*31:0*/ mips_core__DOT__D_CACHE__DOT__databanks__BRA__3__KET____DOT__databank__DOT__new_data;
        IData/*31:0*/ mips_core__DOT__D_CACHE__DOT__databanks__BRA__3__KET____DOT__databank__DOT__old_data;
        IData/*31:0*/ mips_core__DOT__D_CACHE__DOT__databanks__BRA__3__KET____DOT__databank__DOT__genblk1__DOT__BANK_CORE__DOT__din0_reg;
        IData/*31:0*/ mips_core__DOT__HAZARD_CONTROLLER__DOT__BRANCH_CONTROLLER__DOT__PREDICTOR__DOT__unnamedblk1__DOT__i;
        IData/*31:0*/ mips_core__DOT__MEMORY_ARBITER__DOT__write_address_arbiter__DOT__gnt_id;
        IData/*31:0*/ mips_core__DOT__MEMORY_ARBITER__DOT__write_data_arbiter__DOT__gnt_id;
        IData/*31:0*/ mips_core__DOT__MEMORY_ARBITER__DOT__read_address_arbiter__DOT__gnt_id;
        IData/*31:0*/ __Vtask_mips_core__DOT__DECODER__DOT__immediate_raw__6__immediate;
        IData/*31:0*/ __Vtask_mips_core__DOT__DECODER__DOT__immediate_raw__12__immediate;
        IData/*31:0*/ __Vtask_mips_core__DOT__DECODER__DOT__immediate_raw__18__immediate;
        IData/*31:0*/ __Vtask_mips_core__DOT__DECODER__DOT__immediate_raw__24__immediate;
        IData/*31:0*/ __Vtask_mips_core__DOT__DECODER__DOT__immediate_raw__30__immediate;
        IData/*31:0*/ __Vtask_mips_core__DOT__DECODER__DOT__immediate_raw__36__immediate;
        IData/*31:0*/ __Vtask_mips_core__DOT__DECODER__DOT__immediate_raw__42__immediate;
        IData/*31:0*/ __Vtask_mips_core__DOT__DECODER__DOT__immediate_raw__48__immediate;
        IData/*31:0*/ __Vtask_mips_core__DOT__DECODER__DOT__immediate_raw__54__immediate;
        IData/*31:0*/ __Vtask_mips_core__DOT__DECODER__DOT__immediate_raw__60__immediate;
        IData/*31:0*/ __Vtask_mips_core__DOT__DECODER__DOT__immediate_raw__70__immediate;
        IData/*31:0*/ __Vtask_mips_core__DOT__DECODER__DOT__immediate_raw__125__immediate;
        IData/*31:0*/ __Vtask_mips_core__DOT__DECODER__DOT__immediate_raw__147__immediate;
        IData/*31:0*/ __Vtask_mips_core__DOT__DECODER__DOT__immediate_raw__153__immediate;
        IData/*31:0*/ __Vtask_mips_core__DOT__DECODER__DOT__immediate_raw__159__immediate;
        QData/*63:0*/ mips_core__DOT__I_CACHE__DOT__valid_bits;
        QData/*63:0*/ mips_core__DOT__REGISTER_RENAME__DOT__free_reg;
        QData/*63:0*/ mips_core__DOT__REGISTER_RENAME__DOT__reg_ready;
        QData/*63:0*/ mips_core__DOT__D_CACHE__DOT__valid_bits;
        QData/*63:0*/ mips_core__DOT__D_CACHE__DOT__dirty_bits;
        QData/*40:0*/ mips_core__DOT__HAZARD_CONTROLLER__DOT____Vcellinp__BRANCH_CONTROLLER__branch_fb;
        VlWide<3>/*66:0*/ mips_core__DOT__HAZARD_CONTROLLER__DOT__branch_pred_output;
        QData/*33:0*/ mips_core__DOT__MEMORY_ARBITER__DOT____Vcellout__write_address_arbiter__payload;
        QData/*36:0*/ mips_core__DOT__MEMORY_ARBITER__DOT____Vcellout__write_data_arbiter__payload;
        QData/*33:0*/ mips_core__DOT__MEMORY_ARBITER__DOT____Vcellout__read_address_arbiter__payload;
        QData/*33:0*/ mips_core__DOT__MEMORY_ARBITER__DOT__write_address_arbiter__DOT__merged_payload;
        QData/*36:0*/ mips_core__DOT__MEMORY_ARBITER__DOT__write_data_arbiter__DOT__merged_payload;
        QData/*33:0*/ mips_core__DOT__MEMORY_ARBITER__DOT__read_address_arbiter__DOT__merged_payload;
        QData/*36:0*/ mips_core__DOT__MEMORY_ARBITER__DOT__read_data_splitter__DOT__pipe_payload;
        VlWide<3>/*66:0*/ __Vchglast__TOP__mips_core__DOT__HAZARD_CONTROLLER__DOT__branch_pred_output;
        VlUnpacked<IData/*31:0*/, 4> mips_core__DOT__I_CACHE__DOT__databank_wdata;
        VlUnpacked<IData/*31:0*/, 4> mips_core__DOT__I_CACHE__DOT__databank_rdata;
        VlUnpacked<IData/*31:0*/, 4> mips_core__DOT__I_CACHE__DOT__victim_dataline;
        VlUnpacked<IData/*31:0*/, 4> mips_core__DOT__I_CACHE__DOT__databank_dataline;
        VlUnpacked<IData/*31:0*/, 4> mips_core__DOT__I_CACHE__DOT____Vcellout__victim_cache__data_out;
        VlUnpacked<IData/*31:0*/, 4> mips_core__DOT__I_CACHE__DOT____Vcellinp__victim_cache__data_in;
        VlUnpacked<SData/*15:0*/, 4> mips_core__DOT__I_CACHE__DOT__victim_cache__DOT__tag;
    };
    struct {
        VlUnpacked<IData/*31:0*/, 4> mips_core__DOT__I_CACHE__DOT__victim_cache__DOT__data1;
        VlUnpacked<IData/*31:0*/, 4> mips_core__DOT__I_CACHE__DOT__victim_cache__DOT__data2;
        VlUnpacked<IData/*31:0*/, 4> mips_core__DOT__I_CACHE__DOT__victim_cache__DOT__data3;
        VlUnpacked<IData/*31:0*/, 4> mips_core__DOT__I_CACHE__DOT__victim_cache__DOT__data4;
        VlUnpacked<CData/*1:0*/, 4> mips_core__DOT__I_CACHE__DOT__victim_cache__DOT__lru;
        VlUnpacked<CData/*0:0*/, 4> mips_core__DOT__I_CACHE__DOT__victim_cache__DOT__valid;
        VlUnpacked<SData/*15:0*/, 64> mips_core__DOT__I_CACHE__DOT__tagbank__DOT__genblk1__DOT__BANK_CORE__DOT__mem;
        VlUnpacked<IData/*31:0*/, 64> mips_core__DOT__I_CACHE__DOT__databanks__BRA__0__KET____DOT__databank__DOT__genblk1__DOT__BANK_CORE__DOT__mem;
        VlUnpacked<IData/*31:0*/, 64> mips_core__DOT__I_CACHE__DOT__databanks__BRA__1__KET____DOT__databank__DOT__genblk1__DOT__BANK_CORE__DOT__mem;
        VlUnpacked<IData/*31:0*/, 64> mips_core__DOT__I_CACHE__DOT__databanks__BRA__2__KET____DOT__databank__DOT__genblk1__DOT__BANK_CORE__DOT__mem;
        VlUnpacked<IData/*31:0*/, 64> mips_core__DOT__I_CACHE__DOT__databanks__BRA__3__KET____DOT__databank__DOT__genblk1__DOT__BANK_CORE__DOT__mem;
        VlUnpacked<QData/*63:0*/, 2> mips_core__DOT__INSTRUCTION_QUEUE__DOT__inst_queue;
        VlUnpacked<VlWide<5>/*134:0*/, 2> mips_core__DOT__REGISTER_RENAME__DOT__checkpoint_buffer;
        VlUnpacked<CData/*5:0*/, 32> mips_core__DOT__REGISTER_RENAME__DOT__log_res;
        VlUnpacked<CData/*0:0*/, 64> mips_core__DOT__REGISTER_RENAME__DOT__reg_phy_rob_tag;
        VlUnpacked<VlWide<3>/*72:0*/, 2> mips_core__DOT__REORDER_BUFFER__DOT__fifo;
        VlUnpacked<IData/*31:0*/, 64> mips_core__DOT__REG_FILE__DOT__regs;
        VlUnpacked<VlWide<3>/*74:0*/, 2> mips_core__DOT__ALU_RESERVATION_STATION__DOT__reserv_stat_table;
        VlUnpacked<VlWide<4>/*102:0*/, 2> mips_core__DOT__MEM_RESERVATION_STATION__DOT__mem_add_table;
        VlUnpacked<QData/*32:0*/, 2> mips_core__DOT__MEM_RESERVATION_STATION__DOT__store_queue;
        VlUnpacked<IData/*31:0*/, 4> mips_core__DOT__D_CACHE__DOT__databank_rdata;
        VlUnpacked<IData/*31:0*/, 4> mips_core__DOT__D_CACHE__DOT__shift_rdata;
        VlUnpacked<SData/*15:0*/, 64> mips_core__DOT__D_CACHE__DOT__tagbank__DOT__genblk1__DOT__BANK_CORE__DOT__mem;
        VlUnpacked<IData/*31:0*/, 64> mips_core__DOT__D_CACHE__DOT__databanks__BRA__0__KET____DOT__databank__DOT__genblk1__DOT__BANK_CORE__DOT__mem;
        VlUnpacked<IData/*31:0*/, 64> mips_core__DOT__D_CACHE__DOT__databanks__BRA__1__KET____DOT__databank__DOT__genblk1__DOT__BANK_CORE__DOT__mem;
        VlUnpacked<IData/*31:0*/, 64> mips_core__DOT__D_CACHE__DOT__databanks__BRA__2__KET____DOT__databank__DOT__genblk1__DOT__BANK_CORE__DOT__mem;
        VlUnpacked<IData/*31:0*/, 64> mips_core__DOT__D_CACHE__DOT__databanks__BRA__3__KET____DOT__databank__DOT__genblk1__DOT__BANK_CORE__DOT__mem;
        VlUnpacked<VlWide<3>/*66:0*/, 2> mips_core__DOT__HAZARD_CONTROLLER__DOT__bp_buffer;
        VlUnpacked<CData/*1:0*/, 4096> mips_core__DOT__HAZARD_CONTROLLER__DOT__BRANCH_CONTROLLER__DOT__PREDICTOR__DOT__bht_chooser;
        VlUnpacked<CData/*1:0*/, 4096> mips_core__DOT__HAZARD_CONTROLLER__DOT__BRANCH_CONTROLLER__DOT__PREDICTOR__DOT__bht_gshare;
        VlUnpacked<CData/*0:0*/, 1> mips_core__DOT__MEMORY_ARBITER__DOT__write_address_entity_ready;
        VlUnpacked<CData/*0:0*/, 1> mips_core__DOT__MEMORY_ARBITER__DOT__write_address_entity_valid;
        VlUnpacked<QData/*33:0*/, 1> mips_core__DOT__MEMORY_ARBITER__DOT__write_address_entity_payload;
        VlUnpacked<QData/*33:0*/, 1> mips_core__DOT__MEMORY_ARBITER__DOT____Vcellinp__write_address_arbiter__entity_payload;
        VlUnpacked<CData/*0:0*/, 1> mips_core__DOT__MEMORY_ARBITER__DOT____Vcellinp__write_address_arbiter__entity_valid;
        VlUnpacked<CData/*0:0*/, 1> mips_core__DOT__MEMORY_ARBITER__DOT____Vcellout__write_address_arbiter__entity_ready;
        VlUnpacked<CData/*0:0*/, 1> mips_core__DOT__MEMORY_ARBITER__DOT__write_data_entity_ready;
        VlUnpacked<CData/*0:0*/, 1> mips_core__DOT__MEMORY_ARBITER__DOT__write_data_entity_valid;
        VlUnpacked<QData/*36:0*/, 1> mips_core__DOT__MEMORY_ARBITER__DOT__write_data_entity_payload;
        VlUnpacked<QData/*36:0*/, 1> mips_core__DOT__MEMORY_ARBITER__DOT____Vcellinp__write_data_arbiter__entity_payload;
        VlUnpacked<CData/*0:0*/, 1> mips_core__DOT__MEMORY_ARBITER__DOT____Vcellinp__write_data_arbiter__entity_valid;
        VlUnpacked<CData/*0:0*/, 1> mips_core__DOT__MEMORY_ARBITER__DOT____Vcellout__write_data_arbiter__entity_ready;
        VlUnpacked<CData/*0:0*/, 1> mips_core__DOT__MEMORY_ARBITER__DOT__write_response_entity_ready;
        VlUnpacked<CData/*0:0*/, 1> mips_core__DOT__MEMORY_ARBITER__DOT__write_response_entity_valid;
        VlUnpacked<CData/*3:0*/, 1> mips_core__DOT__MEMORY_ARBITER__DOT__write_response_entity_payload;
        VlUnpacked<CData/*3:0*/, 1> mips_core__DOT__MEMORY_ARBITER__DOT____Vcellout__write_response_splitter__entity_payload;
        VlUnpacked<CData/*0:0*/, 1> mips_core__DOT__MEMORY_ARBITER__DOT____Vcellout__write_response_splitter__entity_valid;
        VlUnpacked<CData/*0:0*/, 1> mips_core__DOT__MEMORY_ARBITER__DOT____Vcellinp__write_response_splitter__entity_ready;
        VlUnpacked<CData/*0:0*/, 2> mips_core__DOT__MEMORY_ARBITER__DOT__read_address_entity_ready;
        VlUnpacked<CData/*0:0*/, 2> mips_core__DOT__MEMORY_ARBITER__DOT__read_address_entity_valid;
        VlUnpacked<QData/*33:0*/, 2> mips_core__DOT__MEMORY_ARBITER__DOT__read_address_entity_payload;
        VlUnpacked<QData/*33:0*/, 2> mips_core__DOT__MEMORY_ARBITER__DOT____Vcellinp__read_address_arbiter__entity_payload;
        VlUnpacked<CData/*0:0*/, 2> mips_core__DOT__MEMORY_ARBITER__DOT____Vcellinp__read_address_arbiter__entity_valid;
        VlUnpacked<CData/*0:0*/, 2> mips_core__DOT__MEMORY_ARBITER__DOT____Vcellout__read_address_arbiter__entity_ready;
        VlUnpacked<CData/*0:0*/, 2> mips_core__DOT__MEMORY_ARBITER__DOT__read_data_entity_ready;
        VlUnpacked<CData/*0:0*/, 2> mips_core__DOT__MEMORY_ARBITER__DOT__read_data_entity_valid;
        VlUnpacked<QData/*36:0*/, 2> mips_core__DOT__MEMORY_ARBITER__DOT__read_data_entity_payload;
        VlUnpacked<QData/*36:0*/, 2> mips_core__DOT__MEMORY_ARBITER__DOT____Vcellout__read_data_splitter__entity_payload;
        VlUnpacked<CData/*0:0*/, 2> mips_core__DOT__MEMORY_ARBITER__DOT____Vcellout__read_data_splitter__entity_valid;
        VlUnpacked<CData/*0:0*/, 2> mips_core__DOT__MEMORY_ARBITER__DOT____Vcellinp__read_data_splitter__entity_ready;
        VlUnpacked<CData/*0:0*/, 4> __Vchglast__TOP__mips_core__DOT__I_CACHE__DOT__victim_cache__DOT__valid;
        VlUnpacked<CData/*0:0*/, 5> __Vm_traceActivity;
    };

    // INTERNAL VARIABLES
    Vmips_core__Syms* const vlSymsp;

    // CONSTRUCTORS
    Vmips_core___024root(Vmips_core__Syms* symsp, const char* name);
    ~Vmips_core___024root();
    VL_UNCOPYABLE(Vmips_core___024root);

    // INTERNAL METHODS
    void __Vconfigure(bool first);
} VL_ATTR_ALIGNED(VL_CACHE_LINE_BYTES);


#endif  // guard
