// Verilated -*- C++ -*-
// DESCRIPTION: Verilator output: Design internal header
// See Vmips_core.h for the primary calling header

#ifndef VERILATED_VMIPS_CORE___024ROOT_H_
#define VERILATED_VMIPS_CORE___024ROOT_H_  // guard

#include "verilated.h"

class Vmips_core__Syms;
class Vmips_core___024unit;
class Vmips_core_pc_ifc;
class Vmips_core_cache_output_ifc;
class Vmips_core_decoder_output_ifc;
class Vmips_core_reg_file_output_ifc;
class Vmips_core_branch_decoded_ifc;
class Vmips_core_alu_input_ifc;
class Vmips_core_alu_pass_through_ifc;
class Vmips_core_alu_output_ifc;
class Vmips_core_d_cache_input_ifc;
class Vmips_core_d_cache_pass_through_ifc;
class Vmips_core_write_back_ifc;
class Vmips_core_hazard_control_ifc;

VL_MODULE(Vmips_core___024root) {
  public:
    // CELLS
    Vmips_core___024unit* __PVT____024unit;
    Vmips_core_pc_ifc* __PVT__mips_core__DOT__if_pc_current;
    Vmips_core_pc_ifc* __PVT__mips_core__DOT__if_pc_next;
    Vmips_core_cache_output_ifc* __PVT__mips_core__DOT__if_i_cache_output;
    Vmips_core_pc_ifc* __PVT__mips_core__DOT__i2d_pc;
    Vmips_core_cache_output_ifc* __PVT__mips_core__DOT__i2d_inst;
    Vmips_core_decoder_output_ifc* __PVT__mips_core__DOT__dec_decoder_output;
    Vmips_core_reg_file_output_ifc* __PVT__mips_core__DOT__dec_reg_file_output;
    Vmips_core_reg_file_output_ifc* __PVT__mips_core__DOT__dec_forward_unit_output;
    Vmips_core_branch_decoded_ifc* __PVT__mips_core__DOT__dec_branch_decoded;
    Vmips_core_alu_input_ifc* __PVT__mips_core__DOT__dec_alu_input;
    Vmips_core_alu_pass_through_ifc* __PVT__mips_core__DOT__dec_alu_pass_through;
    Vmips_core_pc_ifc* __PVT__mips_core__DOT__d2e_pc;
    Vmips_core_alu_input_ifc* __PVT__mips_core__DOT__d2e_alu_input;
    Vmips_core_alu_pass_through_ifc* __PVT__mips_core__DOT__d2e_alu_pass_through;
    Vmips_core_alu_output_ifc* __PVT__mips_core__DOT__ex_alu_output;
    Vmips_core_d_cache_input_ifc* __PVT__mips_core__DOT__ex_d_cache_input;
    Vmips_core_d_cache_pass_through_ifc* __PVT__mips_core__DOT__ex_d_cache_pass_through;
    Vmips_core_pc_ifc* __PVT__mips_core__DOT__e2m_pc;
    Vmips_core_d_cache_input_ifc* __PVT__mips_core__DOT__e2m_d_cache_input;
    Vmips_core_d_cache_pass_through_ifc* __PVT__mips_core__DOT__e2m_d_cache_pass_through;
    Vmips_core_cache_output_ifc* __PVT__mips_core__DOT__mem_d_cache_output;
    Vmips_core_write_back_ifc* __PVT__mips_core__DOT__mem_write_back;
    Vmips_core_write_back_ifc* __PVT__mips_core__DOT__m2w_write_back;
    Vmips_core_hazard_control_ifc* __PVT__mips_core__DOT__i2i_hc;
    Vmips_core_hazard_control_ifc* __PVT__mips_core__DOT__i2d_hc;
    Vmips_core_hazard_control_ifc* __PVT__mips_core__DOT__d2e_hc;
    Vmips_core_hazard_control_ifc* __PVT__mips_core__DOT__e2m_hc;
    Vmips_core_hazard_control_ifc* __PVT__mips_core__DOT__m2w_hc;

    // DESIGN SPECIFIC STATE
    // Anonymous structures to workaround compiler member-count bugs
    struct {
        VL_IN8(clk,0,0);
        VL_IN8(rst_n,0,0);
        VL_OUT8(done,0,0);
        VL_IN8(AWREADY,0,0);
        VL_OUT8(AWVALID,0,0);
        VL_OUT8(AWID,3,0);
        VL_OUT8(AWLEN,3,0);
        VL_IN8(WREADY,0,0);
        VL_OUT8(WVALID,0,0);
        VL_OUT8(WLAST,0,0);
        VL_OUT8(WID,3,0);
        VL_OUT8(BREADY,0,0);
        VL_IN8(BVALID,0,0);
        VL_IN8(BID,3,0);
        VL_IN8(ARREADY,0,0);
        VL_OUT8(ARVALID,0,0);
        VL_OUT8(ARID,3,0);
        VL_OUT8(ARLEN,3,0);
        VL_OUT8(RREADY,0,0);
        VL_IN8(RVALID,0,0);
        VL_IN8(RLAST,0,0);
        VL_IN8(RID,3,0);
        CData/*0:0*/ mips_core__DOT__mem_done;
        CData/*0:0*/ mips_core__DOT__lw_hazard;
        CData/*1:0*/ mips_core__DOT__I_CACHE__DOT__state;
        CData/*1:0*/ mips_core__DOT__I_CACHE__DOT__next_state;
        CData/*5:0*/ mips_core__DOT__I_CACHE__DOT__r_index;
        CData/*3:0*/ mips_core__DOT__I_CACHE__DOT__databank_select;
        CData/*3:0*/ mips_core__DOT__I_CACHE__DOT__databank_we;
        CData/*0:0*/ mips_core__DOT__I_CACHE__DOT__hit;
        CData/*0:0*/ mips_core__DOT__I_CACHE__DOT__miss;
        CData/*0:0*/ mips_core__DOT__I_CACHE__DOT__last_refill_word;
        CData/*0:0*/ mips_core__DOT__I_CACHE__DOT__tagbank__DOT__new_data_flag;
        CData/*0:0*/ mips_core__DOT__I_CACHE__DOT__tagbank__DOT__genblk1__DOT__BANK_CORE__DOT__csb0_reg;
        CData/*5:0*/ mips_core__DOT__I_CACHE__DOT__tagbank__DOT__genblk1__DOT__BANK_CORE__DOT__addr0_reg;
        CData/*0:0*/ mips_core__DOT__I_CACHE__DOT__tagbank__DOT__genblk1__DOT__BANK_CORE__DOT__csb1_reg;
        CData/*5:0*/ mips_core__DOT__I_CACHE__DOT__tagbank__DOT__genblk1__DOT__BANK_CORE__DOT__addr1_reg;
        CData/*0:0*/ mips_core__DOT__I_CACHE__DOT__databanks__BRA__0__KET____DOT__databank__DOT__new_data_flag;
        CData/*0:0*/ mips_core__DOT__I_CACHE__DOT__databanks__BRA__0__KET____DOT__databank__DOT__genblk1__DOT__BANK_CORE__DOT__csb0_reg;
        CData/*5:0*/ mips_core__DOT__I_CACHE__DOT__databanks__BRA__0__KET____DOT__databank__DOT__genblk1__DOT__BANK_CORE__DOT__addr0_reg;
        CData/*0:0*/ mips_core__DOT__I_CACHE__DOT__databanks__BRA__0__KET____DOT__databank__DOT__genblk1__DOT__BANK_CORE__DOT__csb1_reg;
        CData/*5:0*/ mips_core__DOT__I_CACHE__DOT__databanks__BRA__0__KET____DOT__databank__DOT__genblk1__DOT__BANK_CORE__DOT__addr1_reg;
        CData/*0:0*/ mips_core__DOT__I_CACHE__DOT__databanks__BRA__1__KET____DOT__databank__DOT__new_data_flag;
        CData/*0:0*/ mips_core__DOT__I_CACHE__DOT__databanks__BRA__1__KET____DOT__databank__DOT__genblk1__DOT__BANK_CORE__DOT__csb0_reg;
        CData/*5:0*/ mips_core__DOT__I_CACHE__DOT__databanks__BRA__1__KET____DOT__databank__DOT__genblk1__DOT__BANK_CORE__DOT__addr0_reg;
        CData/*0:0*/ mips_core__DOT__I_CACHE__DOT__databanks__BRA__1__KET____DOT__databank__DOT__genblk1__DOT__BANK_CORE__DOT__csb1_reg;
        CData/*5:0*/ mips_core__DOT__I_CACHE__DOT__databanks__BRA__1__KET____DOT__databank__DOT__genblk1__DOT__BANK_CORE__DOT__addr1_reg;
        CData/*0:0*/ mips_core__DOT__I_CACHE__DOT__databanks__BRA__2__KET____DOT__databank__DOT__new_data_flag;
        CData/*0:0*/ mips_core__DOT__I_CACHE__DOT__databanks__BRA__2__KET____DOT__databank__DOT__genblk1__DOT__BANK_CORE__DOT__csb0_reg;
        CData/*5:0*/ mips_core__DOT__I_CACHE__DOT__databanks__BRA__2__KET____DOT__databank__DOT__genblk1__DOT__BANK_CORE__DOT__addr0_reg;
        CData/*0:0*/ mips_core__DOT__I_CACHE__DOT__databanks__BRA__2__KET____DOT__databank__DOT__genblk1__DOT__BANK_CORE__DOT__csb1_reg;
        CData/*5:0*/ mips_core__DOT__I_CACHE__DOT__databanks__BRA__2__KET____DOT__databank__DOT__genblk1__DOT__BANK_CORE__DOT__addr1_reg;
        CData/*0:0*/ mips_core__DOT__I_CACHE__DOT__databanks__BRA__3__KET____DOT__databank__DOT__new_data_flag;
        CData/*0:0*/ mips_core__DOT__I_CACHE__DOT__databanks__BRA__3__KET____DOT__databank__DOT__genblk1__DOT__BANK_CORE__DOT__csb0_reg;
        CData/*5:0*/ mips_core__DOT__I_CACHE__DOT__databanks__BRA__3__KET____DOT__databank__DOT__genblk1__DOT__BANK_CORE__DOT__addr0_reg;
        CData/*0:0*/ mips_core__DOT__I_CACHE__DOT__databanks__BRA__3__KET____DOT__databank__DOT__genblk1__DOT__BANK_CORE__DOT__csb1_reg;
        CData/*5:0*/ mips_core__DOT__I_CACHE__DOT__databanks__BRA__3__KET____DOT__databank__DOT__genblk1__DOT__BANK_CORE__DOT__addr1_reg;
        CData/*2:0*/ mips_core__DOT__D_CACHE__DOT__state;
        CData/*2:0*/ mips_core__DOT__D_CACHE__DOT__next_state;
        CData/*0:0*/ mips_core__DOT__D_CACHE__DOT__pending_write_response;
        CData/*5:0*/ mips_core__DOT__D_CACHE__DOT__r_index;
        CData/*3:0*/ mips_core__DOT__D_CACHE__DOT__databank_select;
        CData/*3:0*/ mips_core__DOT__D_CACHE__DOT__databank_we;
        CData/*5:0*/ mips_core__DOT__D_CACHE__DOT__databank_waddr;
    };
    struct {
        CData/*5:0*/ mips_core__DOT__D_CACHE__DOT__databank_raddr;
        CData/*0:0*/ mips_core__DOT__D_CACHE__DOT__hit;
        CData/*0:0*/ mips_core__DOT__D_CACHE__DOT__miss;
        CData/*0:0*/ mips_core__DOT__D_CACHE__DOT__last_flush_word;
        CData/*0:0*/ mips_core__DOT__D_CACHE__DOT__last_refill_word;
        CData/*0:0*/ mips_core__DOT__D_CACHE__DOT__tagbank__DOT__new_data_flag;
        CData/*0:0*/ mips_core__DOT__D_CACHE__DOT__tagbank__DOT__genblk1__DOT__BANK_CORE__DOT__csb0_reg;
        CData/*5:0*/ mips_core__DOT__D_CACHE__DOT__tagbank__DOT__genblk1__DOT__BANK_CORE__DOT__addr0_reg;
        CData/*5:0*/ mips_core__DOT__D_CACHE__DOT__tagbank__DOT__genblk1__DOT__BANK_CORE__DOT__addr1_reg;
        CData/*0:0*/ mips_core__DOT__D_CACHE__DOT__databanks__BRA__0__KET____DOT__databank__DOT__new_data_flag;
        CData/*0:0*/ mips_core__DOT__D_CACHE__DOT__databanks__BRA__0__KET____DOT__databank__DOT__genblk1__DOT__BANK_CORE__DOT__csb0_reg;
        CData/*5:0*/ mips_core__DOT__D_CACHE__DOT__databanks__BRA__0__KET____DOT__databank__DOT__genblk1__DOT__BANK_CORE__DOT__addr0_reg;
        CData/*0:0*/ mips_core__DOT__D_CACHE__DOT__databanks__BRA__0__KET____DOT__databank__DOT__genblk1__DOT__BANK_CORE__DOT__csb1_reg;
        CData/*5:0*/ mips_core__DOT__D_CACHE__DOT__databanks__BRA__0__KET____DOT__databank__DOT__genblk1__DOT__BANK_CORE__DOT__addr1_reg;
        CData/*0:0*/ mips_core__DOT__D_CACHE__DOT__databanks__BRA__1__KET____DOT__databank__DOT__new_data_flag;
        CData/*0:0*/ mips_core__DOT__D_CACHE__DOT__databanks__BRA__1__KET____DOT__databank__DOT__genblk1__DOT__BANK_CORE__DOT__csb0_reg;
        CData/*5:0*/ mips_core__DOT__D_CACHE__DOT__databanks__BRA__1__KET____DOT__databank__DOT__genblk1__DOT__BANK_CORE__DOT__addr0_reg;
        CData/*0:0*/ mips_core__DOT__D_CACHE__DOT__databanks__BRA__1__KET____DOT__databank__DOT__genblk1__DOT__BANK_CORE__DOT__csb1_reg;
        CData/*5:0*/ mips_core__DOT__D_CACHE__DOT__databanks__BRA__1__KET____DOT__databank__DOT__genblk1__DOT__BANK_CORE__DOT__addr1_reg;
        CData/*0:0*/ mips_core__DOT__D_CACHE__DOT__databanks__BRA__2__KET____DOT__databank__DOT__new_data_flag;
        CData/*0:0*/ mips_core__DOT__D_CACHE__DOT__databanks__BRA__2__KET____DOT__databank__DOT__genblk1__DOT__BANK_CORE__DOT__csb0_reg;
        CData/*5:0*/ mips_core__DOT__D_CACHE__DOT__databanks__BRA__2__KET____DOT__databank__DOT__genblk1__DOT__BANK_CORE__DOT__addr0_reg;
        CData/*0:0*/ mips_core__DOT__D_CACHE__DOT__databanks__BRA__2__KET____DOT__databank__DOT__genblk1__DOT__BANK_CORE__DOT__csb1_reg;
        CData/*5:0*/ mips_core__DOT__D_CACHE__DOT__databanks__BRA__2__KET____DOT__databank__DOT__genblk1__DOT__BANK_CORE__DOT__addr1_reg;
        CData/*0:0*/ mips_core__DOT__D_CACHE__DOT__databanks__BRA__3__KET____DOT__databank__DOT__new_data_flag;
        CData/*0:0*/ mips_core__DOT__D_CACHE__DOT__databanks__BRA__3__KET____DOT__databank__DOT__genblk1__DOT__BANK_CORE__DOT__csb0_reg;
        CData/*5:0*/ mips_core__DOT__D_CACHE__DOT__databanks__BRA__3__KET____DOT__databank__DOT__genblk1__DOT__BANK_CORE__DOT__addr0_reg;
        CData/*0:0*/ mips_core__DOT__D_CACHE__DOT__databanks__BRA__3__KET____DOT__databank__DOT__genblk1__DOT__BANK_CORE__DOT__csb1_reg;
        CData/*5:0*/ mips_core__DOT__D_CACHE__DOT__databanks__BRA__3__KET____DOT__databank__DOT__genblk1__DOT__BANK_CORE__DOT__addr1_reg;
        CData/*0:0*/ mips_core__DOT__HAZARD_CONTROLLER__DOT__ic_miss;
        CData/*0:0*/ mips_core__DOT__HAZARD_CONTROLLER__DOT__ds_miss;
        CData/*0:0*/ mips_core__DOT__HAZARD_CONTROLLER__DOT__dec_overload;
        CData/*0:0*/ mips_core__DOT__HAZARD_CONTROLLER__DOT__ex_overload;
        CData/*0:0*/ mips_core__DOT__HAZARD_CONTROLLER__DOT__if_stall;
        CData/*0:0*/ mips_core__DOT__HAZARD_CONTROLLER__DOT__if_flush;
        CData/*0:0*/ mips_core__DOT__HAZARD_CONTROLLER__DOT__dec_stall;
        CData/*0:0*/ mips_core__DOT__HAZARD_CONTROLLER__DOT__dec_flush;
        CData/*0:0*/ mips_core__DOT__MEMORY_ARBITER__DOT____Vcellout__write_address_arbiter__valid;
        CData/*0:0*/ mips_core__DOT__MEMORY_ARBITER__DOT____Vcellout__write_data_arbiter__valid;
        CData/*0:0*/ mips_core__DOT__MEMORY_ARBITER__DOT____Vcellout__write_response_splitter__ready;
        CData/*0:0*/ mips_core__DOT__MEMORY_ARBITER__DOT____Vcellout__read_address_arbiter__valid;
        CData/*0:0*/ mips_core__DOT__MEMORY_ARBITER__DOT____Vcellout__read_data_splitter__ready;
        CData/*0:0*/ mips_core__DOT__MEMORY_ARBITER__DOT__write_address_arbiter__DOT__merged_valid;
        CData/*0:0*/ mips_core__DOT__MEMORY_ARBITER__DOT__write_address_arbiter__DOT__merged_ready;
        CData/*0:0*/ mips_core__DOT__MEMORY_ARBITER__DOT__write_data_arbiter__DOT__merged_valid;
        CData/*0:0*/ mips_core__DOT__MEMORY_ARBITER__DOT__write_data_arbiter__DOT__merged_ready;
        CData/*3:0*/ mips_core__DOT__MEMORY_ARBITER__DOT__write_response_splitter__DOT__pipe_payload;
        CData/*0:0*/ mips_core__DOT__MEMORY_ARBITER__DOT__write_response_splitter__DOT__pipe_valid;
        CData/*0:0*/ mips_core__DOT__MEMORY_ARBITER__DOT__write_response_splitter__DOT__pipe_ready;
        CData/*3:0*/ mips_core__DOT__MEMORY_ARBITER__DOT__write_response_splitter__DOT__pipe_id;
        CData/*0:0*/ mips_core__DOT__MEMORY_ARBITER__DOT__read_address_arbiter__DOT__merged_valid;
        CData/*0:0*/ mips_core__DOT__MEMORY_ARBITER__DOT__read_address_arbiter__DOT__merged_ready;
        CData/*0:0*/ mips_core__DOT__MEMORY_ARBITER__DOT__read_data_splitter__DOT__pipe_valid;
        CData/*0:0*/ mips_core__DOT__MEMORY_ARBITER__DOT__read_data_splitter__DOT__pipe_ready;
        CData/*3:0*/ mips_core__DOT__MEMORY_ARBITER__DOT__read_data_splitter__DOT__pipe_id;
        CData/*4:0*/ __Vtask_mips_core__DOT__DECODER__DOT__rw_raw__11__rw;
        CData/*4:0*/ __Vtask_mips_core__DOT__DECODER__DOT__rw_raw__18__rw;
        CData/*4:0*/ __Vtask_mips_core__DOT__DECODER__DOT__rw_raw__23__rw;
        CData/*4:0*/ __Vtask_mips_core__DOT__DECODER__DOT__rw_raw__29__rw;
        CData/*4:0*/ __Vtask_mips_core__DOT__DECODER__DOT__rw_raw__35__rw;
        CData/*4:0*/ __Vtask_mips_core__DOT__DECODER__DOT__rw_raw__41__rw;
        CData/*4:0*/ __Vtask_mips_core__DOT__DECODER__DOT__rw_raw__47__rw;
        CData/*4:0*/ __Vtask_mips_core__DOT__DECODER__DOT__rw_raw__53__rw;
        CData/*4:0*/ __Vtask_mips_core__DOT__DECODER__DOT__rw_raw__59__rw;
    };
    struct {
        CData/*4:0*/ __Vtask_mips_core__DOT__DECODER__DOT__rw_raw__78__rw;
        CData/*4:0*/ __Vtask_mips_core__DOT__DECODER__DOT__rw_raw__83__rw;
        CData/*4:0*/ __Vtask_mips_core__DOT__DECODER__DOT__rw_raw__88__rw;
        CData/*4:0*/ __Vtask_mips_core__DOT__DECODER__DOT__rw_raw__93__rw;
        CData/*4:0*/ __Vtask_mips_core__DOT__DECODER__DOT__rw_raw__98__rw;
        CData/*4:0*/ __Vtask_mips_core__DOT__DECODER__DOT__rw_raw__103__rw;
        CData/*4:0*/ __Vtask_mips_core__DOT__DECODER__DOT__rw_raw__108__rw;
        CData/*4:0*/ __Vtask_mips_core__DOT__DECODER__DOT__rw_raw__113__rw;
        CData/*4:0*/ __Vtask_mips_core__DOT__DECODER__DOT__rw_raw__118__rw;
        CData/*4:0*/ __Vtask_mips_core__DOT__DECODER__DOT__rw_raw__123__rw;
        CData/*4:0*/ __Vtask_mips_core__DOT__DECODER__DOT__rw_raw__132__rw;
        CData/*4:0*/ __Vtask_mips_core__DOT__DECODER__DOT__rw_raw__137__rw;
        CData/*4:0*/ __Vtask_mips_core__DOT__DECODER__DOT__rw_raw__142__rw;
        CData/*4:0*/ __Vtask_mips_core__DOT__DECODER__DOT__rw_raw__146__rw;
        CData/*4:0*/ __Vtask_mips_core__DOT__DECODER__DOT__rw_raw__152__rw;
        CData/*4:0*/ __Vtask_mips_core__DOT__DECODER__DOT__rw_raw__158__rw;
        CData/*0:0*/ __Vclklast__TOP__clk;
        SData/*15:0*/ mips_core__DOT__I_CACHE__DOT__r_tag;
        SData/*15:0*/ mips_core__DOT__I_CACHE__DOT__tagbank__DOT__new_data;
        SData/*15:0*/ mips_core__DOT__I_CACHE__DOT__tagbank__DOT__old_data;
        SData/*15:0*/ mips_core__DOT__I_CACHE__DOT__tagbank__DOT__genblk1__DOT__BANK_CORE__DOT__din0_reg;
        SData/*15:0*/ mips_core__DOT__D_CACHE__DOT__r_tag;
        SData/*15:0*/ mips_core__DOT__D_CACHE__DOT__tagbank_rdata;
        SData/*15:0*/ mips_core__DOT__D_CACHE__DOT__tagbank__DOT__new_data;
        SData/*15:0*/ mips_core__DOT__D_CACHE__DOT__tagbank__DOT__old_data;
        SData/*15:0*/ mips_core__DOT__D_CACHE__DOT__tagbank__DOT__genblk1__DOT__BANK_CORE__DOT__din0_reg;
        VL_OUT(AWADDR,25,0);
        VL_OUT(WDATA,31,0);
        VL_OUT(ARADDR,25,0);
        VL_IN(RDATA,31,0);
        IData/*31:0*/ mips_core__DOT__I_CACHE__DOT__databanks__BRA__0__KET____DOT__databank__DOT__new_data;
        IData/*31:0*/ mips_core__DOT__I_CACHE__DOT__databanks__BRA__0__KET____DOT__databank__DOT__old_data;
        IData/*31:0*/ mips_core__DOT__I_CACHE__DOT__databanks__BRA__0__KET____DOT__databank__DOT__genblk1__DOT__BANK_CORE__DOT__din0_reg;
        IData/*31:0*/ mips_core__DOT__I_CACHE__DOT__databanks__BRA__1__KET____DOT__databank__DOT__new_data;
        IData/*31:0*/ mips_core__DOT__I_CACHE__DOT__databanks__BRA__1__KET____DOT__databank__DOT__old_data;
        IData/*31:0*/ mips_core__DOT__I_CACHE__DOT__databanks__BRA__1__KET____DOT__databank__DOT__genblk1__DOT__BANK_CORE__DOT__din0_reg;
        IData/*31:0*/ mips_core__DOT__I_CACHE__DOT__databanks__BRA__2__KET____DOT__databank__DOT__new_data;
        IData/*31:0*/ mips_core__DOT__I_CACHE__DOT__databanks__BRA__2__KET____DOT__databank__DOT__old_data;
        IData/*31:0*/ mips_core__DOT__I_CACHE__DOT__databanks__BRA__2__KET____DOT__databank__DOT__genblk1__DOT__BANK_CORE__DOT__din0_reg;
        IData/*31:0*/ mips_core__DOT__I_CACHE__DOT__databanks__BRA__3__KET____DOT__databank__DOT__new_data;
        IData/*31:0*/ mips_core__DOT__I_CACHE__DOT__databanks__BRA__3__KET____DOT__databank__DOT__old_data;
        IData/*31:0*/ mips_core__DOT__I_CACHE__DOT__databanks__BRA__3__KET____DOT__databank__DOT__genblk1__DOT__BANK_CORE__DOT__din0_reg;
        IData/*31:0*/ mips_core__DOT__D_CACHE__DOT__databank_wdata;
        IData/*31:0*/ mips_core__DOT__D_CACHE__DOT__unnamedblk1__DOT__i;
        IData/*31:0*/ mips_core__DOT__D_CACHE__DOT__unnamedblk2__DOT__i;
        IData/*31:0*/ mips_core__DOT__D_CACHE__DOT__databanks__BRA__0__KET____DOT__databank__DOT__new_data;
        IData/*31:0*/ mips_core__DOT__D_CACHE__DOT__databanks__BRA__0__KET____DOT__databank__DOT__old_data;
        IData/*31:0*/ mips_core__DOT__D_CACHE__DOT__databanks__BRA__0__KET____DOT__databank__DOT__genblk1__DOT__BANK_CORE__DOT__din0_reg;
        IData/*31:0*/ mips_core__DOT__D_CACHE__DOT__databanks__BRA__1__KET____DOT__databank__DOT__new_data;
        IData/*31:0*/ mips_core__DOT__D_CACHE__DOT__databanks__BRA__1__KET____DOT__databank__DOT__old_data;
        IData/*31:0*/ mips_core__DOT__D_CACHE__DOT__databanks__BRA__1__KET____DOT__databank__DOT__genblk1__DOT__BANK_CORE__DOT__din0_reg;
        IData/*31:0*/ mips_core__DOT__D_CACHE__DOT__databanks__BRA__2__KET____DOT__databank__DOT__new_data;
        IData/*31:0*/ mips_core__DOT__D_CACHE__DOT__databanks__BRA__2__KET____DOT__databank__DOT__old_data;
        IData/*31:0*/ mips_core__DOT__D_CACHE__DOT__databanks__BRA__2__KET____DOT__databank__DOT__genblk1__DOT__BANK_CORE__DOT__din0_reg;
        IData/*31:0*/ mips_core__DOT__D_CACHE__DOT__databanks__BRA__3__KET____DOT__databank__DOT__new_data;
        IData/*31:0*/ mips_core__DOT__D_CACHE__DOT__databanks__BRA__3__KET____DOT__databank__DOT__old_data;
        IData/*31:0*/ mips_core__DOT__D_CACHE__DOT__databanks__BRA__3__KET____DOT__databank__DOT__genblk1__DOT__BANK_CORE__DOT__din0_reg;
        IData/*31:0*/ mips_core__DOT__MEMORY_ARBITER__DOT__write_address_arbiter__DOT__gnt_id;
        IData/*31:0*/ mips_core__DOT__MEMORY_ARBITER__DOT__write_data_arbiter__DOT__gnt_id;
        IData/*31:0*/ mips_core__DOT__MEMORY_ARBITER__DOT__read_address_arbiter__DOT__gnt_id;
        IData/*31:0*/ __Vtask_mips_core__DOT__DECODER__DOT__immediate_raw__7__immediate;
        IData/*31:0*/ __Vtask_mips_core__DOT__DECODER__DOT__immediate_raw__13__immediate;
        IData/*31:0*/ __Vtask_mips_core__DOT__DECODER__DOT__immediate_raw__19__immediate;
        IData/*31:0*/ __Vtask_mips_core__DOT__DECODER__DOT__immediate_raw__25__immediate;
    };
    struct {
        IData/*31:0*/ __Vtask_mips_core__DOT__DECODER__DOT__immediate_raw__31__immediate;
        IData/*31:0*/ __Vtask_mips_core__DOT__DECODER__DOT__immediate_raw__37__immediate;
        IData/*31:0*/ __Vtask_mips_core__DOT__DECODER__DOT__immediate_raw__43__immediate;
        IData/*31:0*/ __Vtask_mips_core__DOT__DECODER__DOT__immediate_raw__49__immediate;
        IData/*31:0*/ __Vtask_mips_core__DOT__DECODER__DOT__immediate_raw__55__immediate;
        IData/*31:0*/ __Vtask_mips_core__DOT__DECODER__DOT__immediate_raw__61__immediate;
        IData/*31:0*/ __Vtask_mips_core__DOT__DECODER__DOT__immediate_raw__71__immediate;
        IData/*31:0*/ __Vtask_mips_core__DOT__DECODER__DOT__immediate_raw__126__immediate;
        IData/*31:0*/ __Vtask_mips_core__DOT__DECODER__DOT__immediate_raw__148__immediate;
        IData/*31:0*/ __Vtask_mips_core__DOT__DECODER__DOT__immediate_raw__154__immediate;
        IData/*31:0*/ __Vtask_mips_core__DOT__DECODER__DOT__immediate_raw__160__immediate;
        QData/*63:0*/ mips_core__DOT__I_CACHE__DOT__valid_bits;
        QData/*63:0*/ mips_core__DOT__D_CACHE__DOT__valid_bits;
        QData/*63:0*/ mips_core__DOT__D_CACHE__DOT__dirty_bits;
        QData/*33:0*/ mips_core__DOT__MEMORY_ARBITER__DOT____Vcellout__write_address_arbiter__payload;
        QData/*36:0*/ mips_core__DOT__MEMORY_ARBITER__DOT____Vcellout__write_data_arbiter__payload;
        QData/*33:0*/ mips_core__DOT__MEMORY_ARBITER__DOT____Vcellout__read_address_arbiter__payload;
        QData/*33:0*/ mips_core__DOT__MEMORY_ARBITER__DOT__write_address_arbiter__DOT__merged_payload;
        QData/*36:0*/ mips_core__DOT__MEMORY_ARBITER__DOT__write_data_arbiter__DOT__merged_payload;
        QData/*33:0*/ mips_core__DOT__MEMORY_ARBITER__DOT__read_address_arbiter__DOT__merged_payload;
        QData/*36:0*/ mips_core__DOT__MEMORY_ARBITER__DOT__read_data_splitter__DOT__pipe_payload;
        VlUnpacked<IData/*31:0*/, 4> mips_core__DOT__I_CACHE__DOT__databank_rdata;
        VlUnpacked<SData/*15:0*/, 64> mips_core__DOT__I_CACHE__DOT__tagbank__DOT__genblk1__DOT__BANK_CORE__DOT__mem;
        VlUnpacked<IData/*31:0*/, 64> mips_core__DOT__I_CACHE__DOT__databanks__BRA__0__KET____DOT__databank__DOT__genblk1__DOT__BANK_CORE__DOT__mem;
        VlUnpacked<IData/*31:0*/, 64> mips_core__DOT__I_CACHE__DOT__databanks__BRA__1__KET____DOT__databank__DOT__genblk1__DOT__BANK_CORE__DOT__mem;
        VlUnpacked<IData/*31:0*/, 64> mips_core__DOT__I_CACHE__DOT__databanks__BRA__2__KET____DOT__databank__DOT__genblk1__DOT__BANK_CORE__DOT__mem;
        VlUnpacked<IData/*31:0*/, 64> mips_core__DOT__I_CACHE__DOT__databanks__BRA__3__KET____DOT__databank__DOT__genblk1__DOT__BANK_CORE__DOT__mem;
        VlUnpacked<IData/*31:0*/, 32> mips_core__DOT__REG_FILE__DOT__regs;
        VlUnpacked<IData/*31:0*/, 4> mips_core__DOT__D_CACHE__DOT__databank_rdata;
        VlUnpacked<IData/*31:0*/, 4> mips_core__DOT__D_CACHE__DOT__shift_rdata;
        VlUnpacked<SData/*15:0*/, 64> mips_core__DOT__D_CACHE__DOT__tagbank__DOT__genblk1__DOT__BANK_CORE__DOT__mem;
        VlUnpacked<IData/*31:0*/, 64> mips_core__DOT__D_CACHE__DOT__databanks__BRA__0__KET____DOT__databank__DOT__genblk1__DOT__BANK_CORE__DOT__mem;
        VlUnpacked<IData/*31:0*/, 64> mips_core__DOT__D_CACHE__DOT__databanks__BRA__1__KET____DOT__databank__DOT__genblk1__DOT__BANK_CORE__DOT__mem;
        VlUnpacked<IData/*31:0*/, 64> mips_core__DOT__D_CACHE__DOT__databanks__BRA__2__KET____DOT__databank__DOT__genblk1__DOT__BANK_CORE__DOT__mem;
        VlUnpacked<IData/*31:0*/, 64> mips_core__DOT__D_CACHE__DOT__databanks__BRA__3__KET____DOT__databank__DOT__genblk1__DOT__BANK_CORE__DOT__mem;
        VlUnpacked<CData/*0:0*/, 1> mips_core__DOT__MEMORY_ARBITER__DOT__write_address_entity_ready;
        VlUnpacked<CData/*0:0*/, 1> mips_core__DOT__MEMORY_ARBITER__DOT__write_address_entity_valid;
        VlUnpacked<QData/*33:0*/, 1> mips_core__DOT__MEMORY_ARBITER__DOT__write_address_entity_payload;
        VlUnpacked<QData/*33:0*/, 1> mips_core__DOT__MEMORY_ARBITER__DOT____Vcellinp__write_address_arbiter__entity_payload;
        VlUnpacked<CData/*0:0*/, 1> mips_core__DOT__MEMORY_ARBITER__DOT____Vcellinp__write_address_arbiter__entity_valid;
        VlUnpacked<CData/*0:0*/, 1> mips_core__DOT__MEMORY_ARBITER__DOT____Vcellout__write_address_arbiter__entity_ready;
        VlUnpacked<CData/*0:0*/, 1> mips_core__DOT__MEMORY_ARBITER__DOT__write_data_entity_ready;
        VlUnpacked<CData/*0:0*/, 1> mips_core__DOT__MEMORY_ARBITER__DOT__write_data_entity_valid;
        VlUnpacked<QData/*36:0*/, 1> mips_core__DOT__MEMORY_ARBITER__DOT__write_data_entity_payload;
        VlUnpacked<QData/*36:0*/, 1> mips_core__DOT__MEMORY_ARBITER__DOT____Vcellinp__write_data_arbiter__entity_payload;
        VlUnpacked<CData/*0:0*/, 1> mips_core__DOT__MEMORY_ARBITER__DOT____Vcellinp__write_data_arbiter__entity_valid;
        VlUnpacked<CData/*0:0*/, 1> mips_core__DOT__MEMORY_ARBITER__DOT____Vcellout__write_data_arbiter__entity_ready;
        VlUnpacked<CData/*0:0*/, 1> mips_core__DOT__MEMORY_ARBITER__DOT__write_response_entity_ready;
        VlUnpacked<CData/*0:0*/, 1> mips_core__DOT__MEMORY_ARBITER__DOT__write_response_entity_valid;
        VlUnpacked<CData/*3:0*/, 1> mips_core__DOT__MEMORY_ARBITER__DOT__write_response_entity_payload;
        VlUnpacked<CData/*3:0*/, 1> mips_core__DOT__MEMORY_ARBITER__DOT____Vcellout__write_response_splitter__entity_payload;
        VlUnpacked<CData/*0:0*/, 1> mips_core__DOT__MEMORY_ARBITER__DOT____Vcellout__write_response_splitter__entity_valid;
        VlUnpacked<CData/*0:0*/, 1> mips_core__DOT__MEMORY_ARBITER__DOT____Vcellinp__write_response_splitter__entity_ready;
        VlUnpacked<CData/*0:0*/, 2> mips_core__DOT__MEMORY_ARBITER__DOT__read_address_entity_ready;
        VlUnpacked<CData/*0:0*/, 2> mips_core__DOT__MEMORY_ARBITER__DOT__read_address_entity_valid;
        VlUnpacked<QData/*33:0*/, 2> mips_core__DOT__MEMORY_ARBITER__DOT__read_address_entity_payload;
        VlUnpacked<QData/*33:0*/, 2> mips_core__DOT__MEMORY_ARBITER__DOT____Vcellinp__read_address_arbiter__entity_payload;
        VlUnpacked<CData/*0:0*/, 2> mips_core__DOT__MEMORY_ARBITER__DOT____Vcellinp__read_address_arbiter__entity_valid;
        VlUnpacked<CData/*0:0*/, 2> mips_core__DOT__MEMORY_ARBITER__DOT____Vcellout__read_address_arbiter__entity_ready;
        VlUnpacked<CData/*0:0*/, 2> mips_core__DOT__MEMORY_ARBITER__DOT__read_data_entity_ready;
        VlUnpacked<CData/*0:0*/, 2> mips_core__DOT__MEMORY_ARBITER__DOT__read_data_entity_valid;
        VlUnpacked<QData/*36:0*/, 2> mips_core__DOT__MEMORY_ARBITER__DOT__read_data_entity_payload;
        VlUnpacked<QData/*36:0*/, 2> mips_core__DOT__MEMORY_ARBITER__DOT____Vcellout__read_data_splitter__entity_payload;
        VlUnpacked<CData/*0:0*/, 2> mips_core__DOT__MEMORY_ARBITER__DOT____Vcellout__read_data_splitter__entity_valid;
    };
    struct {
        VlUnpacked<CData/*0:0*/, 2> mips_core__DOT__MEMORY_ARBITER__DOT____Vcellinp__read_data_splitter__entity_ready;
        VlUnpacked<CData/*0:0*/, 5> __Vm_traceActivity;
    };

    // INTERNAL VARIABLES
    Vmips_core__Syms* const vlSymsp;

    // CONSTRUCTORS
    Vmips_core___024root(Vmips_core__Syms* symsp, const char* name);
    ~Vmips_core___024root();
    VL_UNCOPYABLE(Vmips_core___024root);

    // INTERNAL METHODS
    void __Vconfigure(bool first);
} VL_ATTR_ALIGNED(VL_CACHE_LINE_BYTES);


#endif  // guard
